version: '3.9'
services:
  mongodb: 
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

volumes:
  mongodb_data:

networks:
  mongodb_network:

  # para correr: docker-compose up -d
  # acceder a CLI mongo: docker exec -it mongodb mongosh